/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPoolsIndexRouteImport } from './routes/user-pools/index'
import { Route as UserPoolsCreateRouteImport } from './routes/user-pools/create'

const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPoolsIndexRoute = UserPoolsIndexRouteImport.update({
  id: '/user-pools/',
  path: '/user-pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPoolsCreateRoute = UserPoolsCreateRouteImport.update({
  id: '/user-pools/create',
  path: '/user-pools/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/user-pools/create': typeof UserPoolsCreateRoute
  '/user-pools/': typeof UserPoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/user-pools/create': typeof UserPoolsCreateRoute
  '/user-pools': typeof UserPoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/user-pools/create': typeof UserPoolsCreateRoute
  '/user-pools/': typeof UserPoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/not-authorized' | '/user-pools/create' | '/user-pools/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/not-authorized' | '/user-pools/create' | '/user-pools'
  id:
    | '__root__'
    | '/'
    | '/not-authorized'
    | '/user-pools/create'
    | '/user-pools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
  UserPoolsCreateRoute: typeof UserPoolsCreateRoute
  UserPoolsIndexRoute: typeof UserPoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-pools/': {
      id: '/user-pools/'
      path: '/user-pools'
      fullPath: '/user-pools/'
      preLoaderRoute: typeof UserPoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-pools/create': {
      id: '/user-pools/create'
      path: '/user-pools/create'
      fullPath: '/user-pools/create'
      preLoaderRoute: typeof UserPoolsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
  UserPoolsCreateRoute: UserPoolsCreateRoute,
  UserPoolsIndexRoute: UserPoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
