/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as IndexRouteImport } from './routes/index'

const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/not-authorized'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/not-authorized'
  id: '__root__' | '/' | '/not-authorized'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
