/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPoolsIndexRouteImport } from './routes/user-pools/index'
import { Route as UserPoolsCreateRouteImport } from './routes/user-pools/create'
import { Route as UserPoolsUserPoolIdRouteImport } from './routes/user-pools/$userPoolId'
import { Route as UserPoolsUserPoolIdIndexRouteImport } from './routes/user-pools/$userPoolId/index'
import { Route as UserPoolsUserPoolIdUsersIndexRouteImport } from './routes/user-pools/$userPoolId/users/index'
import { Route as UserPoolsUserPoolIdResourceServersIndexRouteImport } from './routes/user-pools/$userPoolId/resource-servers/index'
import { Route as UserPoolsUserPoolIdIdentityProvidersIndexRouteImport } from './routes/user-pools/$userPoolId/identity-providers/index'
import { Route as UserPoolsUserPoolIdGroupsIndexRouteImport } from './routes/user-pools/$userPoolId/groups/index'
import { Route as UserPoolsUserPoolIdDomainIndexRouteImport } from './routes/user-pools/$userPoolId/domain/index'
import { Route as UserPoolsUserPoolIdAppClientsIndexRouteImport } from './routes/user-pools/$userPoolId/app-clients/index'
import { Route as UserPoolsUserPoolIdUsersCreateRouteImport } from './routes/user-pools/$userPoolId/users/create'
import { Route as UserPoolsUserPoolIdUsersUsernameRouteImport } from './routes/user-pools/$userPoolId/users/$username'
import { Route as UserPoolsUserPoolIdResourceServersCreateRouteImport } from './routes/user-pools/$userPoolId/resource-servers/create'
import { Route as UserPoolsUserPoolIdResourceServersIdentifierRouteImport } from './routes/user-pools/$userPoolId/resource-servers/$identifier'
import { Route as UserPoolsUserPoolIdIdentityProvidersCreateRouteImport } from './routes/user-pools/$userPoolId/identity-providers/create'
import { Route as UserPoolsUserPoolIdIdentityProvidersProviderNameRouteImport } from './routes/user-pools/$userPoolId/identity-providers/$providerName'
import { Route as UserPoolsUserPoolIdGroupsCreateRouteImport } from './routes/user-pools/$userPoolId/groups/create'
import { Route as UserPoolsUserPoolIdGroupsGroupNameRouteImport } from './routes/user-pools/$userPoolId/groups/$groupName'
import { Route as UserPoolsUserPoolIdAppClientsCreateRouteImport } from './routes/user-pools/$userPoolId/app-clients/create'
import { Route as UserPoolsUserPoolIdAppClientsClientIdRouteImport } from './routes/user-pools/$userPoolId/app-clients/$clientId'
import { Route as UserPoolsUserPoolIdUsersUsernameIndexRouteImport } from './routes/user-pools/$userPoolId/users/$username/index'
import { Route as UserPoolsUserPoolIdResourceServersIdentifierIndexRouteImport } from './routes/user-pools/$userPoolId/resource-servers/$identifier/index'
import { Route as UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRouteImport } from './routes/user-pools/$userPoolId/identity-providers/$providerName/index'
import { Route as UserPoolsUserPoolIdGroupsGroupNameIndexRouteImport } from './routes/user-pools/$userPoolId/groups/$groupName/index'
import { Route as UserPoolsUserPoolIdAppClientsClientIdIndexRouteImport } from './routes/user-pools/$userPoolId/app-clients/$clientId/index'

const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPoolsIndexRoute = UserPoolsIndexRouteImport.update({
  id: '/user-pools/',
  path: '/user-pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPoolsCreateRoute = UserPoolsCreateRouteImport.update({
  id: '/user-pools/create',
  path: '/user-pools/create',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPoolsUserPoolIdRoute = UserPoolsUserPoolIdRouteImport.update({
  id: '/user-pools/$userPoolId',
  path: '/user-pools/$userPoolId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPoolsUserPoolIdIndexRoute =
  UserPoolsUserPoolIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdUsersIndexRoute =
  UserPoolsUserPoolIdUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdResourceServersIndexRoute =
  UserPoolsUserPoolIdResourceServersIndexRouteImport.update({
    id: '/resource-servers/',
    path: '/resource-servers/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdIdentityProvidersIndexRoute =
  UserPoolsUserPoolIdIdentityProvidersIndexRouteImport.update({
    id: '/identity-providers/',
    path: '/identity-providers/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdGroupsIndexRoute =
  UserPoolsUserPoolIdGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdDomainIndexRoute =
  UserPoolsUserPoolIdDomainIndexRouteImport.update({
    id: '/domain/',
    path: '/domain/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdAppClientsIndexRoute =
  UserPoolsUserPoolIdAppClientsIndexRouteImport.update({
    id: '/app-clients/',
    path: '/app-clients/',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdUsersCreateRoute =
  UserPoolsUserPoolIdUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdUsersUsernameRoute =
  UserPoolsUserPoolIdUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdResourceServersCreateRoute =
  UserPoolsUserPoolIdResourceServersCreateRouteImport.update({
    id: '/resource-servers/create',
    path: '/resource-servers/create',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdResourceServersIdentifierRoute =
  UserPoolsUserPoolIdResourceServersIdentifierRouteImport.update({
    id: '/resource-servers/$identifier',
    path: '/resource-servers/$identifier',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdIdentityProvidersCreateRoute =
  UserPoolsUserPoolIdIdentityProvidersCreateRouteImport.update({
    id: '/identity-providers/create',
    path: '/identity-providers/create',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdIdentityProvidersProviderNameRoute =
  UserPoolsUserPoolIdIdentityProvidersProviderNameRouteImport.update({
    id: '/identity-providers/$providerName',
    path: '/identity-providers/$providerName',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdGroupsCreateRoute =
  UserPoolsUserPoolIdGroupsCreateRouteImport.update({
    id: '/groups/create',
    path: '/groups/create',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdGroupsGroupNameRoute =
  UserPoolsUserPoolIdGroupsGroupNameRouteImport.update({
    id: '/groups/$groupName',
    path: '/groups/$groupName',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdAppClientsCreateRoute =
  UserPoolsUserPoolIdAppClientsCreateRouteImport.update({
    id: '/app-clients/create',
    path: '/app-clients/create',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdAppClientsClientIdRoute =
  UserPoolsUserPoolIdAppClientsClientIdRouteImport.update({
    id: '/app-clients/$clientId',
    path: '/app-clients/$clientId',
    getParentRoute: () => UserPoolsUserPoolIdRoute,
  } as any)
const UserPoolsUserPoolIdUsersUsernameIndexRoute =
  UserPoolsUserPoolIdUsersUsernameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserPoolsUserPoolIdUsersUsernameRoute,
  } as any)
const UserPoolsUserPoolIdResourceServersIdentifierIndexRoute =
  UserPoolsUserPoolIdResourceServersIdentifierIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserPoolsUserPoolIdResourceServersIdentifierRoute,
  } as any)
const UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute =
  UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserPoolsUserPoolIdIdentityProvidersProviderNameRoute,
  } as any)
const UserPoolsUserPoolIdGroupsGroupNameIndexRoute =
  UserPoolsUserPoolIdGroupsGroupNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserPoolsUserPoolIdGroupsGroupNameRoute,
  } as any)
const UserPoolsUserPoolIdAppClientsClientIdIndexRoute =
  UserPoolsUserPoolIdAppClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserPoolsUserPoolIdAppClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/user-pools/$userPoolId': typeof UserPoolsUserPoolIdRouteWithChildren
  '/user-pools/create': typeof UserPoolsCreateRoute
  '/user-pools/': typeof UserPoolsIndexRoute
  '/user-pools/$userPoolId/': typeof UserPoolsUserPoolIdIndexRoute
  '/user-pools/$userPoolId/app-clients/$clientId': typeof UserPoolsUserPoolIdAppClientsClientIdRouteWithChildren
  '/user-pools/$userPoolId/app-clients/create': typeof UserPoolsUserPoolIdAppClientsCreateRoute
  '/user-pools/$userPoolId/groups/$groupName': typeof UserPoolsUserPoolIdGroupsGroupNameRouteWithChildren
  '/user-pools/$userPoolId/groups/create': typeof UserPoolsUserPoolIdGroupsCreateRoute
  '/user-pools/$userPoolId/identity-providers/$providerName': typeof UserPoolsUserPoolIdIdentityProvidersProviderNameRouteWithChildren
  '/user-pools/$userPoolId/identity-providers/create': typeof UserPoolsUserPoolIdIdentityProvidersCreateRoute
  '/user-pools/$userPoolId/resource-servers/$identifier': typeof UserPoolsUserPoolIdResourceServersIdentifierRouteWithChildren
  '/user-pools/$userPoolId/resource-servers/create': typeof UserPoolsUserPoolIdResourceServersCreateRoute
  '/user-pools/$userPoolId/users/$username': typeof UserPoolsUserPoolIdUsersUsernameRouteWithChildren
  '/user-pools/$userPoolId/users/create': typeof UserPoolsUserPoolIdUsersCreateRoute
  '/user-pools/$userPoolId/app-clients/': typeof UserPoolsUserPoolIdAppClientsIndexRoute
  '/user-pools/$userPoolId/domain/': typeof UserPoolsUserPoolIdDomainIndexRoute
  '/user-pools/$userPoolId/groups/': typeof UserPoolsUserPoolIdGroupsIndexRoute
  '/user-pools/$userPoolId/identity-providers/': typeof UserPoolsUserPoolIdIdentityProvidersIndexRoute
  '/user-pools/$userPoolId/resource-servers/': typeof UserPoolsUserPoolIdResourceServersIndexRoute
  '/user-pools/$userPoolId/users/': typeof UserPoolsUserPoolIdUsersIndexRoute
  '/user-pools/$userPoolId/app-clients/$clientId/': typeof UserPoolsUserPoolIdAppClientsClientIdIndexRoute
  '/user-pools/$userPoolId/groups/$groupName/': typeof UserPoolsUserPoolIdGroupsGroupNameIndexRoute
  '/user-pools/$userPoolId/identity-providers/$providerName/': typeof UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute
  '/user-pools/$userPoolId/resource-servers/$identifier/': typeof UserPoolsUserPoolIdResourceServersIdentifierIndexRoute
  '/user-pools/$userPoolId/users/$username/': typeof UserPoolsUserPoolIdUsersUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/user-pools/create': typeof UserPoolsCreateRoute
  '/user-pools': typeof UserPoolsIndexRoute
  '/user-pools/$userPoolId': typeof UserPoolsUserPoolIdIndexRoute
  '/user-pools/$userPoolId/app-clients/create': typeof UserPoolsUserPoolIdAppClientsCreateRoute
  '/user-pools/$userPoolId/groups/create': typeof UserPoolsUserPoolIdGroupsCreateRoute
  '/user-pools/$userPoolId/identity-providers/create': typeof UserPoolsUserPoolIdIdentityProvidersCreateRoute
  '/user-pools/$userPoolId/resource-servers/create': typeof UserPoolsUserPoolIdResourceServersCreateRoute
  '/user-pools/$userPoolId/users/create': typeof UserPoolsUserPoolIdUsersCreateRoute
  '/user-pools/$userPoolId/app-clients': typeof UserPoolsUserPoolIdAppClientsIndexRoute
  '/user-pools/$userPoolId/domain': typeof UserPoolsUserPoolIdDomainIndexRoute
  '/user-pools/$userPoolId/groups': typeof UserPoolsUserPoolIdGroupsIndexRoute
  '/user-pools/$userPoolId/identity-providers': typeof UserPoolsUserPoolIdIdentityProvidersIndexRoute
  '/user-pools/$userPoolId/resource-servers': typeof UserPoolsUserPoolIdResourceServersIndexRoute
  '/user-pools/$userPoolId/users': typeof UserPoolsUserPoolIdUsersIndexRoute
  '/user-pools/$userPoolId/app-clients/$clientId': typeof UserPoolsUserPoolIdAppClientsClientIdIndexRoute
  '/user-pools/$userPoolId/groups/$groupName': typeof UserPoolsUserPoolIdGroupsGroupNameIndexRoute
  '/user-pools/$userPoolId/identity-providers/$providerName': typeof UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute
  '/user-pools/$userPoolId/resource-servers/$identifier': typeof UserPoolsUserPoolIdResourceServersIdentifierIndexRoute
  '/user-pools/$userPoolId/users/$username': typeof UserPoolsUserPoolIdUsersUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/user-pools/$userPoolId': typeof UserPoolsUserPoolIdRouteWithChildren
  '/user-pools/create': typeof UserPoolsCreateRoute
  '/user-pools/': typeof UserPoolsIndexRoute
  '/user-pools/$userPoolId/': typeof UserPoolsUserPoolIdIndexRoute
  '/user-pools/$userPoolId/app-clients/$clientId': typeof UserPoolsUserPoolIdAppClientsClientIdRouteWithChildren
  '/user-pools/$userPoolId/app-clients/create': typeof UserPoolsUserPoolIdAppClientsCreateRoute
  '/user-pools/$userPoolId/groups/$groupName': typeof UserPoolsUserPoolIdGroupsGroupNameRouteWithChildren
  '/user-pools/$userPoolId/groups/create': typeof UserPoolsUserPoolIdGroupsCreateRoute
  '/user-pools/$userPoolId/identity-providers/$providerName': typeof UserPoolsUserPoolIdIdentityProvidersProviderNameRouteWithChildren
  '/user-pools/$userPoolId/identity-providers/create': typeof UserPoolsUserPoolIdIdentityProvidersCreateRoute
  '/user-pools/$userPoolId/resource-servers/$identifier': typeof UserPoolsUserPoolIdResourceServersIdentifierRouteWithChildren
  '/user-pools/$userPoolId/resource-servers/create': typeof UserPoolsUserPoolIdResourceServersCreateRoute
  '/user-pools/$userPoolId/users/$username': typeof UserPoolsUserPoolIdUsersUsernameRouteWithChildren
  '/user-pools/$userPoolId/users/create': typeof UserPoolsUserPoolIdUsersCreateRoute
  '/user-pools/$userPoolId/app-clients/': typeof UserPoolsUserPoolIdAppClientsIndexRoute
  '/user-pools/$userPoolId/domain/': typeof UserPoolsUserPoolIdDomainIndexRoute
  '/user-pools/$userPoolId/groups/': typeof UserPoolsUserPoolIdGroupsIndexRoute
  '/user-pools/$userPoolId/identity-providers/': typeof UserPoolsUserPoolIdIdentityProvidersIndexRoute
  '/user-pools/$userPoolId/resource-servers/': typeof UserPoolsUserPoolIdResourceServersIndexRoute
  '/user-pools/$userPoolId/users/': typeof UserPoolsUserPoolIdUsersIndexRoute
  '/user-pools/$userPoolId/app-clients/$clientId/': typeof UserPoolsUserPoolIdAppClientsClientIdIndexRoute
  '/user-pools/$userPoolId/groups/$groupName/': typeof UserPoolsUserPoolIdGroupsGroupNameIndexRoute
  '/user-pools/$userPoolId/identity-providers/$providerName/': typeof UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute
  '/user-pools/$userPoolId/resource-servers/$identifier/': typeof UserPoolsUserPoolIdResourceServersIdentifierIndexRoute
  '/user-pools/$userPoolId/users/$username/': typeof UserPoolsUserPoolIdUsersUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-authorized'
    | '/user-pools/$userPoolId'
    | '/user-pools/create'
    | '/user-pools/'
    | '/user-pools/$userPoolId/'
    | '/user-pools/$userPoolId/app-clients/$clientId'
    | '/user-pools/$userPoolId/app-clients/create'
    | '/user-pools/$userPoolId/groups/$groupName'
    | '/user-pools/$userPoolId/groups/create'
    | '/user-pools/$userPoolId/identity-providers/$providerName'
    | '/user-pools/$userPoolId/identity-providers/create'
    | '/user-pools/$userPoolId/resource-servers/$identifier'
    | '/user-pools/$userPoolId/resource-servers/create'
    | '/user-pools/$userPoolId/users/$username'
    | '/user-pools/$userPoolId/users/create'
    | '/user-pools/$userPoolId/app-clients/'
    | '/user-pools/$userPoolId/domain/'
    | '/user-pools/$userPoolId/groups/'
    | '/user-pools/$userPoolId/identity-providers/'
    | '/user-pools/$userPoolId/resource-servers/'
    | '/user-pools/$userPoolId/users/'
    | '/user-pools/$userPoolId/app-clients/$clientId/'
    | '/user-pools/$userPoolId/groups/$groupName/'
    | '/user-pools/$userPoolId/identity-providers/$providerName/'
    | '/user-pools/$userPoolId/resource-servers/$identifier/'
    | '/user-pools/$userPoolId/users/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-authorized'
    | '/user-pools/create'
    | '/user-pools'
    | '/user-pools/$userPoolId'
    | '/user-pools/$userPoolId/app-clients/create'
    | '/user-pools/$userPoolId/groups/create'
    | '/user-pools/$userPoolId/identity-providers/create'
    | '/user-pools/$userPoolId/resource-servers/create'
    | '/user-pools/$userPoolId/users/create'
    | '/user-pools/$userPoolId/app-clients'
    | '/user-pools/$userPoolId/domain'
    | '/user-pools/$userPoolId/groups'
    | '/user-pools/$userPoolId/identity-providers'
    | '/user-pools/$userPoolId/resource-servers'
    | '/user-pools/$userPoolId/users'
    | '/user-pools/$userPoolId/app-clients/$clientId'
    | '/user-pools/$userPoolId/groups/$groupName'
    | '/user-pools/$userPoolId/identity-providers/$providerName'
    | '/user-pools/$userPoolId/resource-servers/$identifier'
    | '/user-pools/$userPoolId/users/$username'
  id:
    | '__root__'
    | '/'
    | '/not-authorized'
    | '/user-pools/$userPoolId'
    | '/user-pools/create'
    | '/user-pools/'
    | '/user-pools/$userPoolId/'
    | '/user-pools/$userPoolId/app-clients/$clientId'
    | '/user-pools/$userPoolId/app-clients/create'
    | '/user-pools/$userPoolId/groups/$groupName'
    | '/user-pools/$userPoolId/groups/create'
    | '/user-pools/$userPoolId/identity-providers/$providerName'
    | '/user-pools/$userPoolId/identity-providers/create'
    | '/user-pools/$userPoolId/resource-servers/$identifier'
    | '/user-pools/$userPoolId/resource-servers/create'
    | '/user-pools/$userPoolId/users/$username'
    | '/user-pools/$userPoolId/users/create'
    | '/user-pools/$userPoolId/app-clients/'
    | '/user-pools/$userPoolId/domain/'
    | '/user-pools/$userPoolId/groups/'
    | '/user-pools/$userPoolId/identity-providers/'
    | '/user-pools/$userPoolId/resource-servers/'
    | '/user-pools/$userPoolId/users/'
    | '/user-pools/$userPoolId/app-clients/$clientId/'
    | '/user-pools/$userPoolId/groups/$groupName/'
    | '/user-pools/$userPoolId/identity-providers/$providerName/'
    | '/user-pools/$userPoolId/resource-servers/$identifier/'
    | '/user-pools/$userPoolId/users/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
  UserPoolsUserPoolIdRoute: typeof UserPoolsUserPoolIdRouteWithChildren
  UserPoolsCreateRoute: typeof UserPoolsCreateRoute
  UserPoolsIndexRoute: typeof UserPoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-pools/': {
      id: '/user-pools/'
      path: '/user-pools'
      fullPath: '/user-pools/'
      preLoaderRoute: typeof UserPoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-pools/create': {
      id: '/user-pools/create'
      path: '/user-pools/create'
      fullPath: '/user-pools/create'
      preLoaderRoute: typeof UserPoolsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-pools/$userPoolId': {
      id: '/user-pools/$userPoolId'
      path: '/user-pools/$userPoolId'
      fullPath: '/user-pools/$userPoolId'
      preLoaderRoute: typeof UserPoolsUserPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-pools/$userPoolId/': {
      id: '/user-pools/$userPoolId/'
      path: '/'
      fullPath: '/user-pools/$userPoolId/'
      preLoaderRoute: typeof UserPoolsUserPoolIdIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/users/': {
      id: '/user-pools/$userPoolId/users/'
      path: '/users'
      fullPath: '/user-pools/$userPoolId/users/'
      preLoaderRoute: typeof UserPoolsUserPoolIdUsersIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/resource-servers/': {
      id: '/user-pools/$userPoolId/resource-servers/'
      path: '/resource-servers'
      fullPath: '/user-pools/$userPoolId/resource-servers/'
      preLoaderRoute: typeof UserPoolsUserPoolIdResourceServersIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/identity-providers/': {
      id: '/user-pools/$userPoolId/identity-providers/'
      path: '/identity-providers'
      fullPath: '/user-pools/$userPoolId/identity-providers/'
      preLoaderRoute: typeof UserPoolsUserPoolIdIdentityProvidersIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/groups/': {
      id: '/user-pools/$userPoolId/groups/'
      path: '/groups'
      fullPath: '/user-pools/$userPoolId/groups/'
      preLoaderRoute: typeof UserPoolsUserPoolIdGroupsIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/domain/': {
      id: '/user-pools/$userPoolId/domain/'
      path: '/domain'
      fullPath: '/user-pools/$userPoolId/domain/'
      preLoaderRoute: typeof UserPoolsUserPoolIdDomainIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/app-clients/': {
      id: '/user-pools/$userPoolId/app-clients/'
      path: '/app-clients'
      fullPath: '/user-pools/$userPoolId/app-clients/'
      preLoaderRoute: typeof UserPoolsUserPoolIdAppClientsIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/users/create': {
      id: '/user-pools/$userPoolId/users/create'
      path: '/users/create'
      fullPath: '/user-pools/$userPoolId/users/create'
      preLoaderRoute: typeof UserPoolsUserPoolIdUsersCreateRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/users/$username': {
      id: '/user-pools/$userPoolId/users/$username'
      path: '/users/$username'
      fullPath: '/user-pools/$userPoolId/users/$username'
      preLoaderRoute: typeof UserPoolsUserPoolIdUsersUsernameRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/resource-servers/create': {
      id: '/user-pools/$userPoolId/resource-servers/create'
      path: '/resource-servers/create'
      fullPath: '/user-pools/$userPoolId/resource-servers/create'
      preLoaderRoute: typeof UserPoolsUserPoolIdResourceServersCreateRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/resource-servers/$identifier': {
      id: '/user-pools/$userPoolId/resource-servers/$identifier'
      path: '/resource-servers/$identifier'
      fullPath: '/user-pools/$userPoolId/resource-servers/$identifier'
      preLoaderRoute: typeof UserPoolsUserPoolIdResourceServersIdentifierRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/identity-providers/create': {
      id: '/user-pools/$userPoolId/identity-providers/create'
      path: '/identity-providers/create'
      fullPath: '/user-pools/$userPoolId/identity-providers/create'
      preLoaderRoute: typeof UserPoolsUserPoolIdIdentityProvidersCreateRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/identity-providers/$providerName': {
      id: '/user-pools/$userPoolId/identity-providers/$providerName'
      path: '/identity-providers/$providerName'
      fullPath: '/user-pools/$userPoolId/identity-providers/$providerName'
      preLoaderRoute: typeof UserPoolsUserPoolIdIdentityProvidersProviderNameRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/groups/create': {
      id: '/user-pools/$userPoolId/groups/create'
      path: '/groups/create'
      fullPath: '/user-pools/$userPoolId/groups/create'
      preLoaderRoute: typeof UserPoolsUserPoolIdGroupsCreateRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/groups/$groupName': {
      id: '/user-pools/$userPoolId/groups/$groupName'
      path: '/groups/$groupName'
      fullPath: '/user-pools/$userPoolId/groups/$groupName'
      preLoaderRoute: typeof UserPoolsUserPoolIdGroupsGroupNameRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/app-clients/create': {
      id: '/user-pools/$userPoolId/app-clients/create'
      path: '/app-clients/create'
      fullPath: '/user-pools/$userPoolId/app-clients/create'
      preLoaderRoute: typeof UserPoolsUserPoolIdAppClientsCreateRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/app-clients/$clientId': {
      id: '/user-pools/$userPoolId/app-clients/$clientId'
      path: '/app-clients/$clientId'
      fullPath: '/user-pools/$userPoolId/app-clients/$clientId'
      preLoaderRoute: typeof UserPoolsUserPoolIdAppClientsClientIdRouteImport
      parentRoute: typeof UserPoolsUserPoolIdRoute
    }
    '/user-pools/$userPoolId/users/$username/': {
      id: '/user-pools/$userPoolId/users/$username/'
      path: '/'
      fullPath: '/user-pools/$userPoolId/users/$username/'
      preLoaderRoute: typeof UserPoolsUserPoolIdUsersUsernameIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdUsersUsernameRoute
    }
    '/user-pools/$userPoolId/resource-servers/$identifier/': {
      id: '/user-pools/$userPoolId/resource-servers/$identifier/'
      path: '/'
      fullPath: '/user-pools/$userPoolId/resource-servers/$identifier/'
      preLoaderRoute: typeof UserPoolsUserPoolIdResourceServersIdentifierIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdResourceServersIdentifierRoute
    }
    '/user-pools/$userPoolId/identity-providers/$providerName/': {
      id: '/user-pools/$userPoolId/identity-providers/$providerName/'
      path: '/'
      fullPath: '/user-pools/$userPoolId/identity-providers/$providerName/'
      preLoaderRoute: typeof UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdIdentityProvidersProviderNameRoute
    }
    '/user-pools/$userPoolId/groups/$groupName/': {
      id: '/user-pools/$userPoolId/groups/$groupName/'
      path: '/'
      fullPath: '/user-pools/$userPoolId/groups/$groupName/'
      preLoaderRoute: typeof UserPoolsUserPoolIdGroupsGroupNameIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdGroupsGroupNameRoute
    }
    '/user-pools/$userPoolId/app-clients/$clientId/': {
      id: '/user-pools/$userPoolId/app-clients/$clientId/'
      path: '/'
      fullPath: '/user-pools/$userPoolId/app-clients/$clientId/'
      preLoaderRoute: typeof UserPoolsUserPoolIdAppClientsClientIdIndexRouteImport
      parentRoute: typeof UserPoolsUserPoolIdAppClientsClientIdRoute
    }
  }
}

interface UserPoolsUserPoolIdAppClientsClientIdRouteChildren {
  UserPoolsUserPoolIdAppClientsClientIdIndexRoute: typeof UserPoolsUserPoolIdAppClientsClientIdIndexRoute
}

const UserPoolsUserPoolIdAppClientsClientIdRouteChildren: UserPoolsUserPoolIdAppClientsClientIdRouteChildren =
  {
    UserPoolsUserPoolIdAppClientsClientIdIndexRoute:
      UserPoolsUserPoolIdAppClientsClientIdIndexRoute,
  }

const UserPoolsUserPoolIdAppClientsClientIdRouteWithChildren =
  UserPoolsUserPoolIdAppClientsClientIdRoute._addFileChildren(
    UserPoolsUserPoolIdAppClientsClientIdRouteChildren,
  )

interface UserPoolsUserPoolIdGroupsGroupNameRouteChildren {
  UserPoolsUserPoolIdGroupsGroupNameIndexRoute: typeof UserPoolsUserPoolIdGroupsGroupNameIndexRoute
}

const UserPoolsUserPoolIdGroupsGroupNameRouteChildren: UserPoolsUserPoolIdGroupsGroupNameRouteChildren =
  {
    UserPoolsUserPoolIdGroupsGroupNameIndexRoute:
      UserPoolsUserPoolIdGroupsGroupNameIndexRoute,
  }

const UserPoolsUserPoolIdGroupsGroupNameRouteWithChildren =
  UserPoolsUserPoolIdGroupsGroupNameRoute._addFileChildren(
    UserPoolsUserPoolIdGroupsGroupNameRouteChildren,
  )

interface UserPoolsUserPoolIdIdentityProvidersProviderNameRouteChildren {
  UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute: typeof UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute
}

const UserPoolsUserPoolIdIdentityProvidersProviderNameRouteChildren: UserPoolsUserPoolIdIdentityProvidersProviderNameRouteChildren =
  {
    UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute:
      UserPoolsUserPoolIdIdentityProvidersProviderNameIndexRoute,
  }

const UserPoolsUserPoolIdIdentityProvidersProviderNameRouteWithChildren =
  UserPoolsUserPoolIdIdentityProvidersProviderNameRoute._addFileChildren(
    UserPoolsUserPoolIdIdentityProvidersProviderNameRouteChildren,
  )

interface UserPoolsUserPoolIdResourceServersIdentifierRouteChildren {
  UserPoolsUserPoolIdResourceServersIdentifierIndexRoute: typeof UserPoolsUserPoolIdResourceServersIdentifierIndexRoute
}

const UserPoolsUserPoolIdResourceServersIdentifierRouteChildren: UserPoolsUserPoolIdResourceServersIdentifierRouteChildren =
  {
    UserPoolsUserPoolIdResourceServersIdentifierIndexRoute:
      UserPoolsUserPoolIdResourceServersIdentifierIndexRoute,
  }

const UserPoolsUserPoolIdResourceServersIdentifierRouteWithChildren =
  UserPoolsUserPoolIdResourceServersIdentifierRoute._addFileChildren(
    UserPoolsUserPoolIdResourceServersIdentifierRouteChildren,
  )

interface UserPoolsUserPoolIdUsersUsernameRouteChildren {
  UserPoolsUserPoolIdUsersUsernameIndexRoute: typeof UserPoolsUserPoolIdUsersUsernameIndexRoute
}

const UserPoolsUserPoolIdUsersUsernameRouteChildren: UserPoolsUserPoolIdUsersUsernameRouteChildren =
  {
    UserPoolsUserPoolIdUsersUsernameIndexRoute:
      UserPoolsUserPoolIdUsersUsernameIndexRoute,
  }

const UserPoolsUserPoolIdUsersUsernameRouteWithChildren =
  UserPoolsUserPoolIdUsersUsernameRoute._addFileChildren(
    UserPoolsUserPoolIdUsersUsernameRouteChildren,
  )

interface UserPoolsUserPoolIdRouteChildren {
  UserPoolsUserPoolIdIndexRoute: typeof UserPoolsUserPoolIdIndexRoute
  UserPoolsUserPoolIdAppClientsClientIdRoute: typeof UserPoolsUserPoolIdAppClientsClientIdRouteWithChildren
  UserPoolsUserPoolIdAppClientsCreateRoute: typeof UserPoolsUserPoolIdAppClientsCreateRoute
  UserPoolsUserPoolIdGroupsGroupNameRoute: typeof UserPoolsUserPoolIdGroupsGroupNameRouteWithChildren
  UserPoolsUserPoolIdGroupsCreateRoute: typeof UserPoolsUserPoolIdGroupsCreateRoute
  UserPoolsUserPoolIdIdentityProvidersProviderNameRoute: typeof UserPoolsUserPoolIdIdentityProvidersProviderNameRouteWithChildren
  UserPoolsUserPoolIdIdentityProvidersCreateRoute: typeof UserPoolsUserPoolIdIdentityProvidersCreateRoute
  UserPoolsUserPoolIdResourceServersIdentifierRoute: typeof UserPoolsUserPoolIdResourceServersIdentifierRouteWithChildren
  UserPoolsUserPoolIdResourceServersCreateRoute: typeof UserPoolsUserPoolIdResourceServersCreateRoute
  UserPoolsUserPoolIdUsersUsernameRoute: typeof UserPoolsUserPoolIdUsersUsernameRouteWithChildren
  UserPoolsUserPoolIdUsersCreateRoute: typeof UserPoolsUserPoolIdUsersCreateRoute
  UserPoolsUserPoolIdAppClientsIndexRoute: typeof UserPoolsUserPoolIdAppClientsIndexRoute
  UserPoolsUserPoolIdDomainIndexRoute: typeof UserPoolsUserPoolIdDomainIndexRoute
  UserPoolsUserPoolIdGroupsIndexRoute: typeof UserPoolsUserPoolIdGroupsIndexRoute
  UserPoolsUserPoolIdIdentityProvidersIndexRoute: typeof UserPoolsUserPoolIdIdentityProvidersIndexRoute
  UserPoolsUserPoolIdResourceServersIndexRoute: typeof UserPoolsUserPoolIdResourceServersIndexRoute
  UserPoolsUserPoolIdUsersIndexRoute: typeof UserPoolsUserPoolIdUsersIndexRoute
}

const UserPoolsUserPoolIdRouteChildren: UserPoolsUserPoolIdRouteChildren = {
  UserPoolsUserPoolIdIndexRoute: UserPoolsUserPoolIdIndexRoute,
  UserPoolsUserPoolIdAppClientsClientIdRoute:
    UserPoolsUserPoolIdAppClientsClientIdRouteWithChildren,
  UserPoolsUserPoolIdAppClientsCreateRoute:
    UserPoolsUserPoolIdAppClientsCreateRoute,
  UserPoolsUserPoolIdGroupsGroupNameRoute:
    UserPoolsUserPoolIdGroupsGroupNameRouteWithChildren,
  UserPoolsUserPoolIdGroupsCreateRoute: UserPoolsUserPoolIdGroupsCreateRoute,
  UserPoolsUserPoolIdIdentityProvidersProviderNameRoute:
    UserPoolsUserPoolIdIdentityProvidersProviderNameRouteWithChildren,
  UserPoolsUserPoolIdIdentityProvidersCreateRoute:
    UserPoolsUserPoolIdIdentityProvidersCreateRoute,
  UserPoolsUserPoolIdResourceServersIdentifierRoute:
    UserPoolsUserPoolIdResourceServersIdentifierRouteWithChildren,
  UserPoolsUserPoolIdResourceServersCreateRoute:
    UserPoolsUserPoolIdResourceServersCreateRoute,
  UserPoolsUserPoolIdUsersUsernameRoute:
    UserPoolsUserPoolIdUsersUsernameRouteWithChildren,
  UserPoolsUserPoolIdUsersCreateRoute: UserPoolsUserPoolIdUsersCreateRoute,
  UserPoolsUserPoolIdAppClientsIndexRoute:
    UserPoolsUserPoolIdAppClientsIndexRoute,
  UserPoolsUserPoolIdDomainIndexRoute: UserPoolsUserPoolIdDomainIndexRoute,
  UserPoolsUserPoolIdGroupsIndexRoute: UserPoolsUserPoolIdGroupsIndexRoute,
  UserPoolsUserPoolIdIdentityProvidersIndexRoute:
    UserPoolsUserPoolIdIdentityProvidersIndexRoute,
  UserPoolsUserPoolIdResourceServersIndexRoute:
    UserPoolsUserPoolIdResourceServersIndexRoute,
  UserPoolsUserPoolIdUsersIndexRoute: UserPoolsUserPoolIdUsersIndexRoute,
}

const UserPoolsUserPoolIdRouteWithChildren =
  UserPoolsUserPoolIdRoute._addFileChildren(UserPoolsUserPoolIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
  UserPoolsUserPoolIdRoute: UserPoolsUserPoolIdRouteWithChildren,
  UserPoolsCreateRoute: UserPoolsCreateRoute,
  UserPoolsIndexRoute: UserPoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
